### ISSUE TITLE
What to do with chapters

### ISSUE THREAD

**Issue by mvahowe** [mvh-solutions/nice-usfm-json#1]
Before deciding how to do things in JSON, we may need to agree on what USFM and USX do (or rather don't) do.

Syntactically, neither USFM nor USX chapters "enclose" anything. In USFM there would need to be a `\c*` tag. In the case of USX we have

`<chapter number="1" style="c" sid="1CO 1"/>`

which is a milestone, ie it doesn't enclose anything. In USX 2 there was no corresponding

`<chapter eid="1CO 1"/>`

so you only knew that chapter 1 had ended when you hit chapter 2 or EOF. (I think most USX toolchains still work this way because they predate USX3.) It's quite hard to select "all the content in chapter 1" using XSLT or XQuery using that markup, which is how we ended up with massively denormalised sID markup in each paragraph.

So I would argue that enclosing content within chapters is actually a departure from the historical origins of USFM and USX. I don't actually care about that, but I also think that it makes things complicated
- as soon as you have peripherals, or even introductions, because the tree for canonical/non-canonical content is different
- as soon as you want to work across chapters, eg "give me the text for JHN 3:16-4:3"
- if you ever want to support chapters in the middle of a paragraph in a sensible way. (This isn't common but it does happen quite a lot in modern translations.)

With a little tweaking, SOFRIA could do almost exactly what USX did/does, ie
- the chapter label as a paragraph (equivalent to \c)
- verse labels within paragraphs (equivalent to \v)
- chapter and verse scopes within as many paragraphs as necessary (equivalent to sID/eID attributes in USX 3)

**Comment by mvahowe** [comment]
Having slept on this, I still don't think that the USX-type approach provides a very good processing model (although it's still better than a model driven by USFM syntax). I guess that's why I decided to build an alternative to USX :-)

Chapters and verses are always going to be challenging because they do two different things at once
- originally they meant "put some kind of label into your Linotronics here"
- today they are also used to work out what is "in" a chapter or verse

So I don't think there's a perfect solution to be found. I do think, though, that putting chapters at the paragraph level is about the worst possible option.

One big concern for me is that chapter and verses end up behaving completely differently and thus requiring completely different processing. That does reflect USFM syntax, but it doesn't reflect USFM semantics that put chapters and verses in the same chapter, and I would say that it also defies common sense. Outside of the USFM committee, Christians talk about chapters and verses like they are the same kind of thing, and expect them to work together. They understand chapter and verse, they understand "real" paragraphs, they'll never understand how a chapter number can be a paragraph and (in a chapter-nested model) they'll probably ask why chapters include things when verses don't.

On that last point, if you give people a per-chapter structure, the very next question is going to be "why can't I do the same operation again to get one verse?" and I don't think that "because of how people used to mark up text in 1970" counts as a good answer. Either chapter/verse is the fundamental structure of a Bible, or it isn't. So there's a case for chopping up everything by cv like UsfmJs, or by "real" paragraph, but chopping up by chapter but not verse is just inconsistent.

(Yes, verses can span paragraphs... just like chapters...)

In almost cases I process chapters and verses in the same place and with similar code. eg
```
({ context, workspace, output }) => {
                const { element } = context.sequences[0];
                if (element.subType === 'chapter') {
                    workspace.chapter = element.atts['number'];
                    workspace.verses = "0"
                } else if (element.subType === 'verses') {
                    workspace.verses = element.atts['number'];
                }
            }
```
My current solution means that no chapter-specific processing is required, and that feels like a feature.

Putting paragraphs "inside chapters" also imposes a chapter-centric view, regardless of the problem you are trying to solve. In some cases that's a Protestant chapter-centric view, because (contra Tim) \cp is used in ecumenical Bibles to mark up the versification scheme used by the majority of Christians currently alive. If you wanted to split up such a Bible for Catholics, you'd be fighting the Protestant chapter hierarchy all the way.

And this is also true of any other slice-and-dice strategy. Translation sections (\ts\*) don't necessarily contain whole paragraphs only, especially in the case of a parallel text to those milestones. Again, you have to fight the chapter nesting to handle that. Someone might want to render by pericope - same problem. Given that chapters are an archaic structure that is contested by many modern translators, it seems bizarre to force everyone to view everything through that archaic and contested lens.

I often print out Scripture without chapter or verse, "Books of the Bible" style. But if everything is inside chapters I have to deal with chapters regardless, add another level of reduce() or whatever.

Another issue is that having chapter numbers at the same level as "real" paragraphs tends to break type-safeness, (whether or not you are using a strongly-typed language). In SOFRIA, "blocks" are either "real" paragraphs or block grafts (which point to some more blocks you could insert between two paragraphs). A chapter number is a completely different kind of thing. It doesn't have word-level content, you probably don't want to render it using the same process, you may well want to render it in the paragraph you haven't yet opened, if you want to count "real" paragraphs you need to remember to remove the chapter "paragraphs", if your editor works per-block you need special handling for the chapter "paragraphs", and so on and so on.

The difference in structure between canonical and non-canonical text also seems important. One of the "wow" moments of initial Xelah development was when we had canonical text working, and wanted to handle headings and footnotes, and I said "just change the sequence id" and Everything Just Worked. That's possible because the structure of every sequence is identical. If you make canonical text an exception, you need at least two processing models. Any you might need two just for canonical text, given that some DC books have verses before chapter 1. In general, it's really powerful to be able to say

`something.map(...)`

and know that every element will be the same kind of thing.

**Comment by kavitharaju** [comment]
True. USFM/X does not really enclose things using chapter. But I see SOFRIA tries to do that using chapter-wrappers, which I think is a great value addition when accessing content by scopes of chapters.

On the question of **do we put chapter inside paragraph or paragraph inside chapter?** while doing that, I am leaning towards putting paragraph within chapters.
- Its a more intutive structure. I dont think I can agree that a common man you expect to find chapters objects within paragraph objects.
- It complies with the ordering of `c` and `p`s in USFM/X
- Is more general purpose rather than usecase/tool specific

For a USFM like this
```
\c 1
\p
\v 1 ....
\p
\v 10 ...
```
when the current structure is
```
{
"type": "paragraph",
"subtype": "usfm:p",
"content": [
  {
    "type": "wrapper",
    "subtype": "chapter",
    "content": [
      {
        "type": "mark",      //indicating its a real chapter begining
        "subtype": "chapter_label",
        "atts": {
          "number": "1"
        }
      },
      {
        "type": "wrapper",
        "subtype": "verses",
        "content": [
          {
            "type": "mark",
            "subtype": "verses_label",
            "atts": {
              "number": "1"
            }
          },
          "..."
          ]
       }
    ]
  }
},
{
"type": "paragraph",
"subtype": "usfm:p",
"content": [
  {
    "type": "wrapper",
    "subtype": "chapter",
    "content": [
      // absense of a mark object indicating its not a real chapter start
      {
        "type": "wrapper",
        "subtype": "verses",
        "content": [
          {
            "type": "mark",
            "subtype": "verses_label",
            "atts": {
              "number": "10"
            }
          },
          "..."
          ]
       }
    ]
  }
}
```


Can we try to re-wrap it into something like this?
```
{
  type: "wrapper",
  subtype: "chapter",
  content: [
    {
      type: "paragraph",
      subtype: "usfm:p",
      content: [
        {
          type: "wrapper",
          subtype: "verse",
          atts: {number: 1},
          contents: [
            "..."
          ]
        }
      ]
    },
    {
      type: "paragraph",
      subtype: "usfm:p",
      content: [
        {
          type: "wrapper",
          subtype: "verse",
          atts: {number: 10},
          contents: [
            "..."
          ]
        }
      ]
    },
  ]
}
```

:warning: To keep the discussion in the context of chapters, I've not meddled with verse wrapper. But it would be good to not make it a wrapper at all and put both verse numbers and text directly under paragraphs.

- _On peripherals and introductions..._:
	If we need to wrap things together, the `\periph` tag can take the place of chapter and have titles and paragraphs as its contents. That is the order markers take and is the implied semantics, as I understand. In the case of Concordance, glossary etc we dont need to worry about wrapping paragraphs under chapters or periphs and they are go directly under the id/book, just like the introduction paragraphs would.
- _On working across chapters, eg "give me the text for JHN 3:16-4:3"..._:
	I dont think putting chapters under paragraphs make this query any easier unless you are querying for that exact paragraph range that spans across those chapters. Otherwise, for a generic query that spans multiple chapters, we need to anyway scan multiple components. But there is more chance that a query like this would come in terms of chapters than in terms of paragraph divisions and all the more reason to keep chapter over paragraph.
- _On supporting chapters in the middle of a paragraph..._:
	As you also agree, this is a corner case. And USFM does have a way to indicate it, `nb`. Our JSON also only need to represent this information and can leave the processing to the tool.

I would expect that SOFRIA would work well with proskomma internals. But we could keep in mind the understand-ability of the data structure for developers out there who may not be USFM-experts too.

**Comment by mvahowe** [comment]
> To keep the discussion in the context of chapters, I've not meddled with verse wrapper. But it would be good to not make it a wrapper at all and put both verse numbers and text directly under paragraphs.

But then you need to do linear search, potentially across N paragraphs, to find the verse content, and that's really painful if, say, you want to highlight a verse (which is a very common thing to do). I don't understand how chapters need to be a major organising feature but verses don't. If we're implementing "book chapter verse", surely chapters and verses are equally important (however important they are or aren't). In your proposal I'd need a completely different approach for finding chapters and for finding verses. But, conceptually, they are very closely related actions, so why would we make them as different as we possibly can, other than because that's what USFM does? I've seen a lot of attempts at Scripture JSON, and none of them does this because, well, why would you?

Checkout the USFM for SIR at https://diegesis.bible/entry/download/eBible/eng-rv/2022-12-22 . This is a common way to typeset that book in USFM and is just plain wrong, semantically - we have canonical content in an introduction because that's the only way to have content before chapter 1. This is one example of where the current USFM chapter strategy is in my view simply not fit for purpose in an ecumenical world. We have to stop treating the Bibles used by the majority of Christians alive as an edge case...

> I dont think I can agree that a common man would expect to find chapters objects within paragraph objects.

We'd need to ask them :-) But I'm confident that most translators consider clauses, sentences and paragraph to be the natural organising structures of a text, and that chapter/verse often obscures that. Also, I would say that paragraphs (in the normal "a block of text" sense) are the basic organising principle of USFM. Theologically, chapters and verses are non-canonical, not-inerrant additions to the text, and any text can theoretically be used with any cv scheme.

> Our JSON also only need to represent this information and can leave the processing to the tool.

I think this is a fundamental point on which we are disagreeing. I don't think exposing the USFM "data model" as-is is going to give us JSON that most people want to use. It's obviously the easiest solution - both in deciding what to do and getting it past a committee. But, as you say above, it passes all the hard problems to every single dev, and that's why devs continue to make up their own easier solutions. If we want widespread adoption, we need to solve as many of the hard problems as possible.

Also, in your example above, you're using a wrapper for multiple paragraphs. That's the sort of thing that I think makes everything harder. Wrappers are currently for in-paragraph scopes, ie for word/character-level content. That means you can write a handler for wrappers that "does the right thing" for any wrapper. If you make a wrapper "anything that wraps" anything, you can't do that anymore.

FWIW I've made one version of concordances work, but I don't think that USFM is a sensible way to do concordances, or most peripherals. For me it's the identical problem to how MS Office power users end up thinking that an Excel macro is the solution to every problem in the universe. If you only have a hammer, everything looks like a nail. Even Paratext has been moving away from doing everything in USFM.

> I would expect that SOFRIA would work well with proskomma internals. But we could keep in mind the understand-ability of the data structure for developers out there who may not be USFM-experts too.

Actually, Proskomma can't read SOFRIA yet :-) But I take your point. Where we differ is what "easy" looks like. (My first degree is psychology - I don't have any signficant IT qualifications...) So, for me, it's all about the mental model that devs bring to the task. And I would say that, eg, a dev who knows about Bibles but has never processed them is going to expect chapters and verses to behave in a similar way.

Jargon gets a bad press, but it's actually key to mastering non-trivial domains. The USFM spec has particularly disastrous jargon because it repurposes commonly-understood concepts like "paragraph" to include, say, ide metadata, which is guaranteed to trip up every single dev the first time they meet it. Yes, there's jargon around SOFRIA, but I would argue that it's jargon worth learning because, eg, an introduction is a fundamentally different kind of thing to canonical text, and saying "sequence" is easier than saying "a kind of thing you find in a Bible" every time (for which USFM has no name other than maybe in the spec chapter headings). Likewise for grafts - you need a way to say "there's an other optional layer of non-canonical content that could be inserted here".

These are higher-level concepts. USFM doesn't have those at a syntactic level. So you need to know what to do with footnotes, and then with xrefs, and then with headings, and then with titles, and then with sidebars, and if you miss one you either lose canonical text or inline footnote text in your canonical text. (This really does happen all the time - you've probably done it yourself). It's pretty much impossible to do that with SOFRIA. You can ignore all the grafts or process all the grafts or pick which grafts to process, and every graft has the same structure. That just seems like a huge win for new devs, because they only need to learn one structure.

**Comment by mvahowe** [comment]
> I don't think putting chapters under paragraphs make this query any easier unless you are querying for that exact paragraph range that spans across those chapters. Otherwise, for a generic query that spans multiple chapters, we need to anyway scan multiple components.

Can we try this? With my representation, the algorithm is
```
let paras = allParas.filter(paraHasCVRange(cvRange));
paras[0] = trimFromLeft(cvRange);
paras[paras.length - 1] = trimFromRight(cvRange);
return paras;
```
What does your algorithm for paras nested in blocks look like? If I was processing that structure, I'd first do a map that distributed the chapter number across all the blocks so I could then filter on the blocks. In other words, I think the easiest way to process your JSON is to first turn it into my JSON.

It's obviously perfectly possible to work with the tree, but you end up pruning paras in each chapter and finding the first para in the first chapter and the last para in the last chapter, and the result has your verse range split by chapter even though the aim was to get a pericope that spans chapters.

Then we could try to make our algorithms work for, say, a text search for both canonical and non-canonical text. My approach Just Works. Yours only works if you flatten the canonical data or add an artificial extra layer of nesting for peripherals.

Then we could try to make our algorithms work for cp instead of c. Mine just works because chapter and verse are no different to any other milestone markup. Your algorithm has to look completely different because chapters are a special case.

As a rule of thumb, I would say that anything that can be done with cascading maps and filters counts as easy in most modern languages, and that both those operations can also be performed within a streaming processing model. As soon as you add reduce or, especially, tree walking, things get harder.

> But there is more chance that a query like this would come in terms of chapters than in terms of paragraph divisions and all the more reason to keep chapter over paragraph.

Paragraphs are an almost universal unit of structure in modern languages. Everyone understands paragraphs (the non-USFM kind). They also convey translator decisions about how sentences should be grouped. That's why we preserve "real" paragraphs and treat them as a special case. Beyond that, I don't think we should make any one markup system a basic structuring principle, especially as chapters on their own are almost always half of a chapter-verse key where verses are handled in a completely different way.

**Comment by mvahowe** [comment]
I am starting to think that a cv milestone rather than separate chapter and verse milestones would make things even easier.

**Comment by kavitharaju** [comment]
There is a lot to unpack and process in the above responses, which I am trying to do. :smile: 

In the meanwhile I will try to justify why I think, "chapters can be wrappers and verses need not be". 
Point #1: When I hear wrapper, I would expect it to _wrap the object as a whole_, not as different pieces across multiple wrappings. With chapters, if we bring it outside of paragraphs, we can have it wholly wrapped in one object. But verses are frequently seen as spread across paragraphs and is not straight forward be wrapped wholly unless we break the paragraph structures.(But if we really need to treat it as a wrapper my suggestion is to accumulate full text of that verse in that object itself as `attrib.text`. This will meet the expectations of a BCV structure expecting user). 
Point #2: For uniformity of paragraph-text relation, by attaching the text contents directly to the paragraph object. This approach will suit for paragraph in different contexts in USFM, say within chapters(scripture), in `esb`, in `periph` or in `ip`s. In the last three there may not be verses. So for a user he can always find text directly within paragraph-type objects and doesn't need to go within an additional verse-wrapper in one context.

In our JSON we now have
- All text belonging to paragraph
- Verse numbers also belonging to paragraph at same level as text
- If a text component is a verseText, denote it with "type:versetext" and also have a `ref` field marking up the CV info in it. So, the logic of your `paraHasCVRange(cvRange)` can easily be implemented at text level.

**Comment by jcuenod** [comment]
I'm totally new to this space but have some interest in it, so here's my 2c (feel free to completely ignore it). I understand a lot of tradeoffs are being made. One that occurs to me is to make **paragraph breaks milestones** as well.

I realize that there's something semantic going on with paragraphs (especially if they open "poetic" sections, for example). But it solves the problem of nesting in the same way as using milestones for `chv`s.

I'm imagining something like:
```
[
  ...
  { type: "milestone", milestoneType: "p" },
  { type: "text", content: "some verse text..." },
  { type: "milestone", milestoneType: "ch", content: 11 },
  { type: "milestone", milestoneType: "v", content: 1 },
  { type: "milestone", milestoneType: "p" },
  { type: "milestone", milestoneType: "p" },
  { type: "v", content: 2 },
  ...
]
```

It would be good to have the spec determine whether chapters/verses precede paragraphs when they occur together, which may comes down to a decision of hierarchy anyway.

I have more thoughts about more complex data structures that are not "plain" text (like tagged words and footnotes), but I'll refrain from making this comment longer than necessary.

**Comment by mhosken** [comment]
USX 3 all the way! in USX 3, chapters and verses are milestones. The difference is that chapter milestones occur between paragraphs while verse milestones occur within paragraphs. Currently milestones in USX are contained as paragraph content (in a para, cell or note). I can see us extending that to allow a different class of milestones that can occur between paragraphs like chapters do. But that won't be in this version of USFM/X and could take a while to happen, if ever and may take some concrete use case requests to happen.

In effect <chapter> and <verse> are privileged <ms> and <chapter> can go where a <ms> cannot go.

The current USFM model based on occursunder will almost certainly disappear and instead USFM markers will be identified by where they fit into the grammar. So while \p occurs under \c at the moment, it will not remain that way (he says so confidently!) and that USFM will be brought into line with USX regarding these high level content model structures. This means that \p will not be in a \c and \c will not be in a \p, they will be at the same level.

**Comment by alilland** [comment]
> > I dont think I can agree that a common man would expect to find chapters objects within paragraph objects.
> 
> We'd need to ask them :-) But I'm confident that most translators consider clauses, sentences and paragraph to be the natural organising structures of a text, and that chapter/verse often obscures that. Also, I would say that paragraphs (in the normal "a block of text" sense) are the basic organising principle of USFM. Theologically, chapters and verses are non-canonical, not-inerrant additions to the text, and any text can theoretically be used with any cv scheme.

as a lay preacher leading bible studies most nights of the week, who reads my bible daily and talks to regular every day christians on a daily basis, but also a full time software developer i strongly support a chapter first mentality over paragraph first - i fully understand the theological background of paragraphs being a stronger way to communicate thought. But still for the regular person the chapter is more valuable when looking things up. Its not a show stopper for a developer to support multi chapter searches, its certainly not hard to do a lookup on the database or in memory store for two chapters and render a subset of verses on screen.

Chapters are by no means going to disappear from peoples common everyday experience, everyone "thinks" chapter first because of history, and i dont think USFM will trump the way things have been printed for hundreds of years. Most people know as they are reading to look up the chapter before it for context as needed, its only the bible scholars that are going to be looking up things across multiple chapters by en-large. Client applications can still support those lookups on a client by client basis.
